/* תחקיר — all UI text in one place. Question labels are NOT here: he owns
   those and edits them inside the app. */
(function (g) {
  'use strict';

  g.T = {
    app: 'תחקיר',

    navHome: 'בית',     capHome: 'HOME',
    navLog: 'טיסות',    capLog: 'LOG',
    navTrends: 'מגמות', capTrends: 'TRENDS',
    navSet: 'הגדרות',   capSet: 'SETUP',

    /* home */
    statusReady: 'מוכן',
    statusBriefed: 'תודרך',
    hDate: 'תאריך',
    briefTitle: 'תדריך',        capBrief: 'BRIEF',
    debriefTitle: 'תחקיר',      capDebrief: 'DEBRIEF',
    newBrief: 'תדריך חדש',
    openBrief: 'השלמת תחקיר',
    briefWaiting: 'תדריך פתוח, ממתין לתחקיר',
    noBriefYet: 'אין תדריך פתוח',
    noBriefHint: 'מלא תדריך לפני הטיסה. הוא יזין את התחקיר אחריה.',
    briefsWaiting: function (n) {
      return n === 1 ? 'תדריך פתוח, ממתין לתחקיר' : n + ' תדריכים ממתינים לתחקיר';
    },
    alsoWaiting: 'ממתינים גם',
    goalsCarried: 'יעדים',
    goalsCarriedHint: 'יעד שלא הושג חוזר בטיסה הבאה מאותה קטגוריה.',
    goalsNextHint: 'היעדים האלה יחכו לטיסה הבאה מאותה קטגוריה.',
    goalsPulled: function (n) {
      return n === 1 ? 'יעד אחד מהטיסה הקודמת נוסף' : n + ' יעדים מהטיסה הקודמת נוספו';
    },
    noGoals: 'אין יעדים פתוחים',
    noGoalsHint: 'יעדים שתגדיר בסוף התחקיר יופיעו כאן.',
    addGoal: 'הוספת יעד',
    recent: 'טיסות אחרונות',
    viewAll: 'הכל',
    noFlights: 'אין עדיין טיסות',
    noFlightsHint: 'הטיסה הראשונה תופיע כאן. הכל נשמר במכשיר הזה בלבד.',

    /* readouts */
    rMinutes: 'דקות',     capMinutes: 'MINUTES',
    rHours: 'שעות טיסה', capHours: 'HOURS',
    rFlights: 'טיסות',    capFlights: 'FLIGHTS',
    rGoals: 'יעדים',      capGoals: 'GOALS MET',
    rWeek: 'השבוע',       capWeek: 'THIS WEEK',
    rSolo: 'אישור לסולו', capSolo: 'SOLO THIS WEEK',

    /* forms */
    save: 'שמירה',
    saveBrief: 'שמירת תדריך',
    saveDebrief: 'שמירת תחקיר',
    saveChanges: 'שמירת שינויים',
    draftSaving: 'AUTOSAVE',
    draftSaved: 'SAVED',
    yourAnswer: 'התשובה שלך',
    fromBrief: 'מהתדריך',
    briefedNote: 'תודרך',
    addExercise: 'הוספת תרגיל',
    addPoint: 'הוספת נקודה',
    pointsAdded: function (n) { return n === 1 ? 'נקודה נוספה' : n + ' נקודות נוספו'; },
    dragHint: 'גרור כדי לסדר מחדש',
    reorder: 'שינוי סדר',
    pasteList: 'הדבקת רשימה',
    pasteListHint: 'הדבק או הקלד את כל הסילבוס, שורה אחת לכל תרגיל. כל שורה תהפוך לתרגיל נפרד עם מקום להערות.',
    exerciseNotes: 'מה קרה בתרגיל הזה',
    exerciseFocus: 'דגשים לתרגיל',
    loadSyllabus: 'טעינה מהסילבוס',
    noSyllabusFor: function (s) { return '"' + s + '" לא נמצאה בסילבוס. אפשר להוסיף תרגילים ידנית.'; },
    syllabusFilled: function (n) { return n + ' תרגילים נטענו מהסילבוס'; },
    replaceSyllabus: 'להחליף את הסילבוס הקיים?',
    replaceSyllabusBody: 'התרגילים שכתבת יוחלפו בתרגילים מהסילבוס של הגיחה הזו.',
    goalMet: 'הושג',
    goalMissed: 'לא הושג',
    minutesUnit: 'דק׳',
    editBrief: 'עריכת התדריך',

    /* the two-stage loop, explained once, on an empty home screen */
    startTitle: 'איך זה עובד',
    startB1: 'לפני הטיסה ממלאים תדריך: נושא, יעדים, וסילבוס.',
    startB2: 'מקלידים את הגיחה ("AW 3") והתרגילים מהסילבוס נטענים לבד.',
    startB3: 'אחרי הנחיתה משלימים תחקיר. יעד שלא הושג חוזר לטיסה הבאה מאותה קטגוריה.',
    startGo: 'נתחיל',

    /* backup */
    backupNow: 'ייצוא גיבוי',
    backupHomeTitle: 'הטיסות שלך קיימות רק בטלפון הזה.',
    backupHomeBody: 'ייצא קובץ גיבוי ושמור אותו איפשהו. לוקח שתי שניות.',

    /* drafts */
    draftRestored: 'שוחזרה טיוטה שלא נשמרה',
    draftBadge: 'טיוטה',
    draftDiscard: 'התחלה מחדש',
    draftDiscardBody: 'הטיוטה תימחק והטופס יחזור למה שנשמר.',

    /* log */
    search: 'חיפוש בכל התשובות',
    searchSyllabus: 'חיפוש גיחה או תרגיל',
    selectAllShown: 'בחר את המוצגים',
    noMatches: 'אין תוצאות',
    noMatchesHint: 'נסה מילה אחרת או נקה את הסינון.',
    all: 'הכל',
    categories: 'קטגוריות',
    carriedToNext: 'עבר ליעדים לטיסה הבאה',
    awaiting: 'ממתין לתחקיר',

    /* weekly summary */
    selectMode: 'בחירה ידנית',
    weekSummary: 'סיכום השבוע',
    nThisWeek: function (n) { return n === 1 ? 'טיסה אחת השבוע' : n + ' טיסות השבוע'; },
    noneThisWeek: 'אין טיסות השבוע',
    pickManually: 'בחירה ידנית של טיסות',
    selectWeek: 'בחר את השבוע',
    clearSel: 'ניקוי',
    nSelected: function (n) { return n + ' נבחרו'; },
    makeSummary: 'יצירת סיכום',
    summary: 'סיכום',
    summaryTitle: 'סיכום שבועי',
    summaryCustom: 'סיכום טיסות',
    summaryOf: function (a, b) { return a + ' עד ' + b; },
    summaryStats: function (f, m) { return f + ' טיסות · ' + m + ' דקות'; },
    docStats: function (f, h) { return f + ' טיסות · ' + h + ' שעות'; },
    docSolo: function (a, b) { return 'אישור לסולו ' + a + '/' + b; },
    alsoFlown: 'גם: ',
    secGoals: 'יעדים',
    goalsMet: 'הושגו',
    goalsMissed: 'לא הושגו',
    secRepeatGoals: 'יעדים שחוזרים על עצמם',
    secFocus: 'דגשים שחזרו',
    secExercises: 'תרגילים שבוצעו',
    secPoints: 'נקודות עיקריות',
    secSafety: 'בטיחות',
    secFlights: 'פירוט הטיסות',
    timesN: function (n) { return n === 1 ? 'פעם אחת' : n + ' פעמים'; },
    inNFlights: function (n) { return 'ב־' + n + ' טיסות'; },
    recurringTag: 'חוזר',
    noneSelected: 'לא נבחרו טיסות',
    noneSelectedHint: 'סמן את הטיסות שתרצה לסכם ולחץ יצירת סיכום.',
    copyDoc: 'העתקה למסמך',
    exportDoc: 'ייצוא כמסמך',
    docHint: 'הקובץ נפתח ב־Google Docs. אפשר גם להעתיק ולהדביק ישירות למסמך חדש.',
    copiedDoc: 'הועתק, אפשר להדביק ל־Google Docs',

    /* detail */
    copyText: 'העתקה כטקסט',
    deleteFlight: 'מחיקת הטיסה',
    notAnswered: 'לא נענה',
    share: 'שיתוף',
    edit: 'עריכה',

    /* trends */
    trendsEmpty: 'אין עדיין מה להראות',
    trendsEmptyHint: 'אחרי כמה תחקירים יופיע כאן מה חוזר על עצמו.',
    flightsPerWeek: 'טיסות לשבוע',
    lastWeeks: '8 השבועות האחרונים',
    goalRate: 'עמידה ביעדים',
    repeatedGoals: 'יעדים שחוזרים',
    missedGoals: 'יעדים שלא הושגו',
    readAcross: 'תשובה אחת לאורך כל הטיסות',
    nothingHere: 'עדיין לא נכתב כאן דבר.',
    totalMinutes: 'סך שעות',

    /* syllabus progress */
    sylProgress: 'התקדמות בסילבוס',
    sylDone: function (a, b) { return a + ' מתוך ' + b + ' גיחות'; },
    sylNext: 'הבא בתור',
    sylNextNone: 'סיימת את כל הגיחות שבסילבוס.',
    sylFlown: 'בוצעה',
    sylOpenChart: 'הסילבוס המלא',
    sylNoneYet: 'עוד לא נרשמה גיחה שמופיעה בסילבוס.',

    /* instructors */
    byInstructor: 'לפי מדריך',
    instFlights: function (n) { return n === 1 ? 'טיסה אחת' : n + ' טיסות'; },
    instSeeAll: 'הצג את הטיסות',
    instNone: 'לא נרשם מדריך באף טיסה.',

    /* settings */
    settings: 'הגדרות',
    appearance: 'מראה',
    themeDark: 'לילה', themeLight: 'יום', themeAuto: 'אוטומטי',
    questions: 'שאלות',
    questionsHint: 'הוספה, שינוי שם, סידור ומחיקה. השינויים חלים על הטיסה הבאה.',
    stageBrief: 'תדריך', stageDebrief: 'תחקיר',
    addQuestion: 'הוספת שאלה',
    editQuestion: 'עריכת שאלה',
    qLabel: 'שם השאלה',
    qType: 'סוג תשובה',
    qStage: 'באיזה טופס',
    qOptions: 'אפשרויות',
    qOptionsHint: 'אפשרות אחת בכל שורה',
    qInDebrief: 'בתחקיר',
    qInEdit: 'ניתן לעריכה',
    qInReadonly: 'לקריאה בלבד',
    qInNone: 'לא מופיע',
    lockedQuestion: 'שאלת מערכת. אפשר לשנות שם, אי אפשר למחוק.',
    moveUp: 'העלאה', moveDown: 'הורדה',
    restoreDefaults: 'שחזור ברירת המחדל',
    syllabusRef: 'סילבוס האימונים',
    syllabusRefSub: function (n) { return n ? n + ' גיחות' : 'עדיין לא נטען'; },
    syllabusRefEmpty: 'הסילבוס עדיין לא נטען',
    syllabusRefEmptyHint: 'כשהטבלה תיטען, כל גיחה תופיע כאן והתרגילים שלה ייכנסו לתדריך אוטומטית.',
    yourData: 'המידע שלך',
    exportCsv: 'ייצוא לגיליון', exportCsvSub: 'CSV',
    exportJson: 'ייצוא גיבוי', exportJsonSub: 'JSON, משחזר הכל',
    importJson: 'שחזור מגיבוי', importJsonSub: 'מתמזג עם מה שקיים',
    privacy: 'פרטיות',
    setCode: 'הגדרת קוד כניסה', changeCode: 'שינוי קוד הכניסה', removeCode: 'ביטול קוד הכניסה',
    codeOn: 'פעיל', codeOff: 'כבוי', needsHttps: 'דורש כתובת מאובטחת',
    privacyNote: 'לאפליקציה אין חשבון ואין שרת. שום דבר שנכתב כאן לא יוצא מהמכשיר. ' +
                 'קוד הכניסה מונע ממישהו שמרים את הטלפון לקרוא, אבל הוא לא מצפין את הקובץ.',
    deleteAll: 'מחיקת כל הטיסות',
    cannotUndo: 'לא ניתן לשחזר',
    offline: 'עובד גם בלי רשת',
    onDevice: 'טיסות במכשיר',

    backupTitle: 'כדאי לגבות.',
    backupNever: 'עוד לא ייצאת גיבוי.',
    backupDays: function (n) { return 'הגיבוי האחרון היה לפני ' + n + ' ימים.'; },
    backupBody: 'הכל קיים רק בטלפון הזה. ייצא קובץ ושמור אותו במקום בטוח.',

    installTitle: 'הוספה למסך הבית',
    installBodyIOS: 'לחץ על כפתור השיתוף ואז "הוסף למסך הבית". האפליקציה תיפתח במסך מלא ותעבוד גם בלי קליטה.',
    installBodyAndroid: 'פתח את תפריט שלוש הנקודות ובחר "התקנת אפליקציה". היא תיפתח במסך מלא ותעבוד גם בלי קליטה.',
    installBodyGeneric: 'הוסף את האפליקציה למסך הבית. היא תיפתח במסך מלא ותעבוד גם בלי קליטה.',
    installNow: 'התקנה',
    installedToast: 'נוספה למסך הבית',
    gotIt: 'הבנתי',

    /* undo */
    undo: 'החזרה',
    restoredToast: 'הטיסה הוחזרה',
    sessionStale: 'לא היה אפשר לאמת מול Google בלי רשת. תתבקש להיכנס שוב כשתהיה קליטה.',

    /* google sign-in gate */
    gateBody: 'האפליקציה פתוחה רק לחשבונות מאושרים.',
    gateSignIn: 'כניסה עם Google',
    gateChecking: 'בודק…',
    gateDenied: function (e) { return 'החשבון ' + e + ' לא מאושר לאפליקציה הזו.'; },
    gateDeniedNote: 'אפשר לנסות עם חשבון אחר.',
    gateOther: 'חשבון אחר',
    gateFailed: 'ההתחברות לא הושלמה.',
    gateRetry: 'נסה שוב',
    gateOffline: 'צריך חיבור לרשת רק בהתחברות הראשונה. אחר כך האפליקציה נפתחת גם בלי קליטה.',
    gateNoNet: 'אין חיבור לרשת כרגע.',
    account: 'חשבון',
    signedInAs: function (e) { return 'מחובר כ־' + e; },
    signOut: 'התנתקות',
    confirmSignOut: 'להתנתק?',
    confirmSignOutBody: 'הטיסות נשארות במכשיר. תצטרך להיכנס שוב עם Google כדי לפתוח את האפליקציה.',

    /* course selection */
    courseTitle: 'שלב ההכשרה',
    coursePrompt: 'באיזה שלב אתה נמצא?',
    courseBody: 'הבחירה קובעת את הסילבוס, קטגוריות הטיסה והיעדים המומלצים שיוצגו לך.',
    courseConfirm: 'אישור',
    courseSuggested: 'זוהה עבורך',
    courseChangeable: 'ניתן לשנות בכל עת בהגדרות.',
    courseSection: 'שלב ההכשרה',
    courseCurrent: function (n) { return 'קורס ' + n; },
    courseChange: 'שינוי שלב הכשרה',
    courseChangeTitle: function (n) { return 'לעבור לקורס ' + n + '?'; },
    courseChangeBody: 'הסילבוס והקטגוריות יתחלפו. הטיסות שכבר רשומות נשמרות כמו שהן ' +
                      'ונשארות משויכות לקורס שבו בוצעו.',
    courseSwitched: function (n) { return 'עברת לקורס ' + n; },
    courseTag: function (n) { return 'קורס ' + n; },
    courseSyllabusCount: function (n, c) { return n + ' גיחות · קורס ' + c; },

    /* syllabus suggestions */
    simBadge: 'מאמן',
    simHint: 'גיחת מאמן. קיימת גם גיחה באוויר באותו מספר.',
    pickGicha: 'איזו גיחה?',
    pickGichaBody: 'יש כמה גיחות בשם הזה. בחר את הנכונה כדי לטעון את הסילבוס שלה.',
    pickedGicha: 'יש כמה גיחות בשם הזה. נטענה המסתברת ביותר, אפשר להחליף בלחיצה.',
    suggestedGoals: 'יעדים מומלצים מהסילבוס',
    goalsSuggested: function (n) { return n === 1 ? 'יעד מומלץ נוסף' : n + ' יעדים מומלצים נוספו'; },
    plannedMinutes: function (n) { return 'משך מתוכנן ' + n + ' דק׳'; },
    gichaNote: 'הערות לגיחה',
    gichaInstNote: 'הערות למאמן',

    enterCode: 'הזן את הקוד',
    wrongCode: 'קוד שגוי',
    chooseCode: 'בחר קוד בן 4 ספרות',
    repeatCode: 'הזן שוב',
    codeMismatch: 'הקודים לא תואמים. נסה שוב.',
    codeOnToast: 'קוד הכניסה הופעל',
    codeOffToast: 'קוד הכניסה בוטל',
    codeFailed: 'לא ניתן להגדיר קוד כאן',

    cancel: 'ביטול', confirm: 'אישור', add: 'הוספה', remove: 'הסרה', delete: 'מחיקה',
    today: 'היום', yesterday: 'אתמול',
    daysAgo: function (n) { return 'לפני ' + n + ' ימים'; },
    savedToast: 'נשמר',
    briefSavedToast: 'התדריך נשמר',
    debriefSavedToast: 'התחקיר נשמר',
    deletedToast: 'נמחק',
    copiedToast: 'הועתק',
    needSomething: 'מלא לפחות שדה אחד לפני שמירה',

    typeText: 'שורה', typeTextarea: 'טקסט', typeChoice: 'בחירה',
    typeNumber: 'מספר', typeMinutes: 'דקות', typeDate: 'תאריך',
    typeGoals: 'יעדים', typeSyllabus: 'סילבוס', typeList: 'רשימה',

    confirmDeleteFlight: function (d) { return 'למחוק את הטיסה מ־' + d + '?'; },
    confirmDeleteBody: 'הטיסה תימחק מהמכשיר הזה. לא ניתן לשחזר.',
    confirmDeleteAll: function (n) { return 'למחוק את כל ' + n + ' הטיסות?'; },
    confirmDeleteAllBody: 'הכל יימחק מהמכשיר. ייצא גיבוי קודם אם יש סיכוי שתרצה את זה בעתיד.',
    confirmDeleteQuestion: function (q) { return 'למחוק את "' + q + '"?'; },
    confirmDeleteQuestionBody: 'השאלה לא תופיע בטפסים חדשים. תשובות קיימות יישמרו ויוצגו בטיסות הישנות.',
    confirmCodeOff: 'לבטל את קוד הכניסה?',
    confirmCodeOffBody: 'כל מי שירים את הטלפון יוכל לפתוח את האפליקציה.'
  };
})(window);
