/* תחקיר — all UI text in one place. Question labels are NOT here: he owns
   those and edits them inside the app. */
(function (g) {
  'use strict';

  g.T = {
    app: 'תחקיר',

    navHome: 'בית',     capHome: 'HOME',
    navLog: 'טיסות',    capLog: 'LOG',
    navTrends: 'מגמות', capTrends: 'TRENDS',
    navSet: 'הגדרות',   capSet: 'SETUP',

    /* home */
    statusReady: 'מוכן',
    statusBriefed: 'תודרך',
    hDate: 'תאריך',
    briefTitle: 'תדריך',        capBrief: 'BRIEF',
    debriefTitle: 'תחקיר',      capDebrief: 'DEBRIEF',
    newBrief: 'תדריך חדש',
    openBrief: 'השלמת תחקיר',
    briefWaiting: 'תדריך פתוח, ממתין לתחקיר',
    noBriefYet: 'אין תדריך פתוח',
    noBriefHint: 'מלא תדריך לפני הטיסה. הוא יזין את התחקיר אחריה.',
    goalsCarried: 'יעדים שעברו',
    goalsCarriedHint: 'יעדים שלא הושגו עוברים לטיסה הבאה עד שהם מסומנים.',
    noGoals: 'אין יעדים פתוחים',
    noGoalsHint: 'יעדים שתגדיר בסוף התחקיר יופיעו כאן.',
    addGoal: 'הוספת יעד',
    recent: 'טיסות אחרונות',
    viewAll: 'הכל',
    noFlights: 'אין עדיין טיסות',
    noFlightsHint: 'הטיסה הראשונה תופיע כאן. הכל נשמר במכשיר הזה בלבד.',

    /* readouts */
    rMinutes: 'דקות',     capMinutes: 'MINUTES',
    rFlights: 'טיסות',    capFlights: 'FLIGHTS',
    rGoals: 'יעדים',      capGoals: 'GOALS MET',
    rWeek: 'השבוע',       capWeek: 'THIS WEEK',

    /* forms */
    save: 'שמירה',
    saveBrief: 'שמירת תדריך',
    saveDebrief: 'שמירת תחקיר',
    saveChanges: 'שמירת שינויים',
    draftSaving: 'AUTOSAVE',
    draftSaved: 'SAVED',
    yourAnswer: 'התשובה שלך',
    fromBrief: 'מהתדריך',
    briefedNote: 'תודרך',
    addExercise: 'הוספת תרגיל',
    pasteList: 'הדבקת רשימה',
    pasteListHint: 'הדבק או הקלד את כל הסילבוס, שורה אחת לכל תרגיל. כל שורה תהפוך לתרגיל נפרד עם מקום להערות.',
    exerciseNotes: 'מה קרה בתרגיל הזה',
    goalMet: 'הושג',
    goalMissed: 'לא הושג',
    minutesUnit: 'דק׳',
    editBrief: 'עריכת התדריך',

    /* log */
    search: 'חיפוש בכל התשובות',
    noMatches: 'אין תוצאות',
    noMatchesHint: 'נסה מילה אחרת או נקה את הסינון.',
    all: 'הכל',
    awaiting: 'ממתין לתחקיר',

    /* detail */
    copyText: 'העתקה כטקסט',
    deleteFlight: 'מחיקת הטיסה',
    notAnswered: 'לא נענה',
    share: 'שיתוף',
    edit: 'עריכה',

    /* trends */
    trendsEmpty: 'אין עדיין מה להראות',
    trendsEmptyHint: 'אחרי כמה תחקירים יופיע כאן מה חוזר על עצמו.',
    flightsPerWeek: 'טיסות לשבוע',
    lastWeeks: '8 השבועות האחרונים',
    goalRate: 'עמידה ביעדים',
    repeatedGoals: 'יעדים שחוזרים',
    readAcross: 'תשובה אחת לאורך כל הטיסות',
    nothingHere: 'עדיין לא נכתב כאן דבר.',
    totalMinutes: 'סך דקות',

    /* settings */
    settings: 'הגדרות',
    appearance: 'מראה',
    themeDark: 'לילה', themeLight: 'יום', themeAuto: 'אוטומטי',
    questions: 'שאלות',
    questionsHint: 'הוספה, שינוי שם, סידור ומחיקה. השינויים חלים על הטיסה הבאה.',
    stageBrief: 'תדריך', stageDebrief: 'תחקיר',
    addQuestion: 'הוספת שאלה',
    editQuestion: 'עריכת שאלה',
    qLabel: 'שם השאלה',
    qType: 'סוג תשובה',
    qStage: 'באיזה טופס',
    qOptions: 'אפשרויות',
    qOptionsHint: 'אפשרות אחת בכל שורה',
    qInDebrief: 'בתחקיר',
    qInEdit: 'ניתן לעריכה',
    qInReadonly: 'לקריאה בלבד',
    qInNone: 'לא מופיע',
    lockedQuestion: 'שאלת מערכת. אפשר לשנות שם, אי אפשר למחוק.',
    moveUp: 'העלאה', moveDown: 'הורדה',
    restoreDefaults: 'שחזור ברירת המחדל',
    yourData: 'המידע שלך',
    exportCsv: 'ייצוא לגיליון', exportCsvSub: 'CSV',
    exportJson: 'ייצוא גיבוי', exportJsonSub: 'JSON, משחזר הכל',
    importJson: 'שחזור מגיבוי', importJsonSub: 'מתמזג עם מה שקיים',
    privacy: 'פרטיות',
    setCode: 'הגדרת קוד כניסה', changeCode: 'שינוי קוד הכניסה', removeCode: 'ביטול קוד הכניסה',
    codeOn: 'פעיל', codeOff: 'כבוי', needsHttps: 'דורש כתובת מאובטחת',
    privacyNote: 'לאפליקציה אין חשבון ואין שרת. שום דבר שנכתב כאן לא יוצא מהמכשיר. ' +
                 'קוד הכניסה מונע ממישהו שמרים את הטלפון לקרוא, אבל הוא לא מצפין את הקובץ.',
    deleteAll: 'מחיקת כל הטיסות',
    cannotUndo: 'לא ניתן לשחזר',
    offline: 'עובד גם בלי רשת',
    onDevice: 'טיסות במכשיר',

    backupTitle: 'כדאי לגבות.',
    backupNever: 'עוד לא ייצאת גיבוי.',
    backupDays: function (n) { return 'הגיבוי האחרון היה לפני ' + n + ' ימים.'; },
    backupBody: 'הכל קיים רק בטלפון הזה. ייצא קובץ ושמור אותו במקום בטוח.',

    installTitle: 'הוספה למסך הבית',
    installBody: 'לחץ על כפתור השיתוף ואז "הוסף למסך הבית". האפליקציה תיפתח במסך מלא ותעבוד גם בלי קליטה.',
    gotIt: 'הבנתי',

    enterCode: 'הזן את הקוד',
    wrongCode: 'קוד שגוי',
    chooseCode: 'בחר קוד בן 4 ספרות',
    repeatCode: 'הזן שוב',
    codeMismatch: 'הקודים לא תואמים. נסה שוב.',
    codeOnToast: 'קוד הכניסה הופעל',
    codeOffToast: 'קוד הכניסה בוטל',
    codeFailed: 'לא ניתן להגדיר קוד כאן',

    cancel: 'ביטול', confirm: 'אישור', add: 'הוספה', remove: 'הסרה', delete: 'מחיקה',
    today: 'היום', yesterday: 'אתמול',
    daysAgo: function (n) { return 'לפני ' + n + ' ימים'; },
    savedToast: 'נשמר',
    briefSavedToast: 'התדריך נשמר',
    debriefSavedToast: 'התחקיר נשמר',
    deletedToast: 'נמחק',
    copiedToast: 'הועתק',
    needSomething: 'מלא לפחות שדה אחד לפני שמירה',

    typeText: 'שורה', typeTextarea: 'טקסט', typeChoice: 'בחירה',
    typeNumber: 'מספר', typeMinutes: 'דקות', typeDate: 'תאריך',
    typeGoals: 'יעדים', typeSyllabus: 'סילבוס',

    confirmDeleteFlight: function (d) { return 'למחוק את הטיסה מ־' + d + '?'; },
    confirmDeleteBody: 'הטיסה תימחק מהמכשיר הזה. לא ניתן לשחזר.',
    confirmDeleteAll: function (n) { return 'למחוק את כל ' + n + ' הטיסות?'; },
    confirmDeleteAllBody: 'הכל יימחק מהמכשיר. ייצא גיבוי קודם אם יש סיכוי שתרצה את זה בעתיד.',
    confirmDeleteQuestion: function (q) { return 'למחוק את "' + q + '"?'; },
    confirmDeleteQuestionBody: 'השאלה לא תופיע בטפסים חדשים. תשובות קיימות יישמרו ויוצגו בטיסות הישנות.',
    confirmCodeOff: 'לבטל את קוד הכניסה?',
    confirmCodeOffBody: 'כל מי שירים את הטלפון יוכל לפתוח את האפליקציה.'
  };
})(window);
