const assert=require('assert/strict'),{browser}=require('./support.cjs');
let b,checks=0;async function eq(label,expression,expected){const actual=await b.ev(expression);assert.deepEqual(actual,expected,label);checks++;console.log('PASS '+label);}
(async()=>{
 b=await browser();
 await b.route('notebook','[data-newnote]');await b.click('[data-newfolder]');await b.type('#folderTitle','מחשבות');await b.click('#sheet [data-act="0"]');await b.click('[data-newnote]');await b.until("!!document.querySelector('#noteBody')");
 await b.type('#noteTitle','עמוד לבדיקה');await b.type('#noteBody','מחשבה קצרה שנשמרת\nושורה נוספת');await b.type('#notePriority','2');
 await b.route('home','[data-new]');await eq('notebook autosaves on leaving',"Workspace.all().notes.map(n=>({title:n.title,body:n.body,priority:n.priority}))",[{title:'עמוד לבדיקה',body:'מחשבה קצרה שנשמרת\nושורה נוספת',priority:2}]);
 await b.route('notebook','[data-newnote]');await b.shot('notebook');
 const note=await b.ev('Workspace.all().notes[0].id');await b.route('notebook/'+note,'#noteBody');await eq('note reopens intact',"document.querySelector('#noteBody').value",'מחשבה קצרה שנשמרת\nושורה נוספת');await b.shot('notebook-page');
 await b.route('home','[data-new]');
 await b.ev("Store.save({id:'long',stage:'done',answers:{q_subject:'duration',q_minutes:120,q_syllabus:[{id:'ex',text:'exercise',focus:'focus',notes:'important note'}]}})");
 await b.route('debrief/long','[data-minutes]');await eq('duration opens as 120',"document.querySelector('[data-minutes]').value",'120');await b.click('[data-save]');await b.until("document.body.dataset.route==='flight'");await eq('duration remains 120 after save',"Store.get('long').answers.q_minutes",120);
 await b.route('brief/long','[data-save]');await b.click('[data-save]');await b.until("document.body.dataset.route==='home'");await eq('brief route preserves debrief exercise notes',"Store.get('long').answers.q_syllabus[0].notes",'important note');
 await b.route('brief','[data-q=q_subject]');await b.type('[data-q=q_subject]','unique duplicate test');await b.ev("window.countBefore=Store.count();const button=document.querySelector('[data-save]');button.click();button.click();");await b.until("document.body.dataset.route==='home'");await eq('two Save clicks create one flight','Store.count()-countBefore',1);
 await b.route('brief','[data-goalinput=q_goals]');await b.type('[data-goalinput=q_goals]','unfinished goal');await b.route('notebook','[data-newnote]');await b.route('brief','[data-goalinput=q_goals]');await eq('pending add-field survives notebook visit',"document.querySelector('[data-goalinput=q_goals]').value",'unfinished goal');
 await b.click('[data-save]');await b.until("document.body.dataset.route==='home'");await eq('Save commits pending goal',"Store.all().some(r=>(r.answers.q_goals||[]).some(g=>g.text==='unfinished goal'))",true);
 await b.ev("Store.save({id:'grade',stage:'brief',answers:{q_subject:'AW 3',q_goals:[{id:'grade-goal',text:'goal',status:'open'}]}})");
 await b.route('debrief/grade','[data-v=missed]');await b.click('[data-v=missed]');await b.route('notebook','[data-newnote]');await b.route('debrief/grade','[data-v=met]');await b.click('[data-v=met]');await eq('resumed achieved goal removes only its generated next goal',"document.querySelectorAll('[data-goals=q_goals_next] .goalrow').length",0);await b.click('[data-save]');await b.until("document.body.dataset.route==='flight'");
 await b.route('home','[data-new]');await b.ev("Store.setCourse('mitkadem');Store.save({id:'old-course',course:'rishoni',stage:'done',answers:{q_subject:'מבנה 1'}})");
 await b.route('progress','[data-shareprogress]');await eq('wrong-course record does not count in progress',"document.querySelector('.journey__reading strong').textContent",'0%');
 await b.click('[data-addmilestone]');await b.type('#milestoneTitle','אבן דרך אישית');await b.click('#milestoneShare');await b.click('#sheet [data-act="0"]');await b.shot('progress');await b.click('[data-shareprogress]');await b.until("!!document.querySelector('.share-preview')");await eq('share card is a 1080 by 1350 image',"new Promise(resolve=>{const img=document.querySelector('.share-preview');if(img.complete)resolve([img.naturalWidth,img.naturalHeight]);else img.onload=()=>resolve([img.naturalWidth,img.naturalHeight]);})",[1080,1350]);await b.shot('share-card');await b.ev("document.querySelector('#sheet').close()");
 await b.route('brief','[data-q=q_subject]');await b.type('[data-q=q_subject]','הכנות 1');await b.until("document.querySelectorAll('.is-suggested').length>0 && document.querySelectorAll('[data-pick]').length>1");await b.type('.is-suggested input','edited personal goal');await b.click('[data-pick="0"]');await eq('changing candidate protects edited goal with confirmation',"document.querySelector('#sheet').open",true);await b.click('#sheet [data-act="0"]');await eq('edited suggested goal survives confirmed replacement',"Array.from(document.querySelectorAll('[data-goals=q_goals] input')).some(e=>e.value==='edited personal goal')",true);
 await b.route('log','[data-weeksum]');await b.ev('Store.clearDraft()');await b.route('brief','[data-q=q_subject]');const empty=await b.ev("SyllabusRef.all().find(e=>!e.items.length&&e.goals.length).name");await b.type('[data-q=q_subject]',empty);await b.until("document.querySelectorAll('[data-goals=q_goals] .goalrow').length>0");await eq('entry without exercises still loads goals',"document.querySelectorAll('[data-goals=q_goals] .goalrow').length",await b.ev('SyllabusRef.lookup('+JSON.stringify(empty)+').goals.length'));
 await b.route('log','[data-weeksum]');await b.ev("Store.clearDraft();Store.setCourse('rishoni')");await b.route('brief','[data-q=q_subject]');await b.click('[data-fill=q_subject][data-val="AW 3"]');await b.until("document.querySelectorAll('[data-ex] .ex').length>0");checks++;console.log('PASS past subject suggestion autofills syllabus');
 await b.route('log','[data-weeksum]');await b.ev("(async()=>{await Store.save({id:'very-old',flownAt:'2020-01-01',stage:'done',answers:{q_subject:'outside week'}});await Store.save({id:'unfinished-week',stage:'brief',answers:{q_subject:'pending only',q_syllabus:[{text:'unflown exercise'}]}});sessionStorage.setItem('sortie:sel',JSON.stringify({'very-old':true}));window.oldDocument=1;})()");
 await b.send('Page.reload');await b.until("typeof oldDocument==='undefined' && !!document.querySelector('[data-weeksum]')");await b.click('[data-weeksum]');await b.until("!!document.querySelector('[data-copydoc]')");await eq('weekly shortcut excludes old selection and unfinished flights',"(()=>{const s=JSON.parse(sessionStorage.getItem('sortie:sel'));return [!!s['very-old'],!!s['unfinished-week'],document.body.innerText.includes('unflown exercise')];})()",[false,false,false]);
 await b.ev("window.ClipboardItem=undefined;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async t=>{window.copied=t;}}});document.querySelector('[data-copydoc]').click()");await b.until("typeof copied==='string'");await eq('plain summary has no document CSS',"copied.includes('font-family')",false);
 await b.route('trends','[data-tlf]');await eq('main points available in answer history',"!!document.querySelector('[data-tlf=q_points]')",true);
 await b.route('feedback','#feedbackMessage');await b.type('#feedbackMessage','משוב שנשאר בטיוטה');await b.route('home','[data-new]');await b.route('feedback','#feedbackMessage');await eq('feedback draft survives navigation',"document.querySelector('#feedbackMessage').value",'משוב שנשאר בטיוטה');await b.shot('feedback');
 await b.route('settings','[data-act=recovery]');await b.shot('settings');await b.route('whatsnew','[data-understood]');await b.shot('whatsnew');
 await b.route('recovery','[data-fullbackup]');await b.shot('recovery');
 for(const route of ['home','notebook','progress','settings','trends','log']){await b.route(route,'#view');await eq(route+' fits 390px viewport',"document.documentElement.scrollWidth<=document.documentElement.clientWidth",true);}
 await b.route('home','[data-new]');await b.shot('home');await b.ev("Store.set('theme','light')");await b.route('settings','[data-theme-set=light]');await b.click('[data-theme-set=light]');await b.route('progress','[data-shareprogress]');await b.shot('progress-light');
 await eq('no uncaught browser exceptions','true',b.errors.length===0);
 console.log(checks+' browser checks passed');b.close();
})().catch(e=>{console.error(e);if(b){console.error('Runtime errors',JSON.stringify(b.errors));b.close();}process.exitCode=1;});
