const assert=require('assert/strict'),{store}=require('./support.cjs');
let checks=0;function check(label,fn){fn();checks++;console.log('PASS '+label);}
(async()=>{
 const a=store();await a.S.init();a.S.setCourse('mitkadem');a.S.updateQuestion('q_points',{label:'נקודות אישיות'});a.S.removeQuestion('q_area');
 await a.S.save({id:'backup-flight',stage:'done',answers:{q_subject:'מבנה 1',q_goals_next:[{text:'waiting'}],q_syllabus:[{text:'row',focus:'focus',notes:'notes'}]}});
 a.S.saveDraft({id:'new-draft',draftNew:true,answers:{q_subject:'draft'},buffers:{'goalinput:q_goals':'unfinished'}},'brief');
 const folder=a.W.folder('מחשבות');const note=a.W.saveNote({title:'מחשבה',body:'תוכן עברי',folder:folder.id,priority:2});a.W.milestone({course:'mitkadem',title:'checkpoint',share:false});
 const b=store();await b.S.init();await b.S.importJSON(a.S.toJSON());
 check('backup restores flights, shelf, question edits, archive, course, buffers, notebook and milestones',()=>{
  assert.equal(b.S.count(),1);assert.equal(b.S.nextGoals().length,1);assert.equal(b.S.question('q_points').label,'נקודות אישיות');assert.equal(b.S.question('q_area').archived,true);
  assert.equal(b.S.courseId(),'mitkadem');assert.equal(b.S.readDraft().buffers['goalinput:q_goals'],'unfinished');assert.equal(b.W.note(note.id).body,'תוכן עברי');assert.equal(b.W.all().milestones.length,1);
 });
 await b.S.importJSON(a.S.toJSON());check('repeat import is idempotent',()=>{assert.equal(b.S.count(),1);assert.equal(b.S.nextGoals().length,1);assert.equal(b.W.all().notes.length,1);});
 const before=b.S.toJSON();assert.throws(()=>b.S.importJSON(JSON.stringify({questions:[{id:'new-q',label:'new'}],flights:[{id:'valid',answers:{}},null]})));
 check('invalid import makes no changes',()=>{const lhs=JSON.parse(before),rhs=JSON.parse(b.S.toJSON());delete lhs.exportedAt;delete rhs.exportedAt;assert.deepEqual(rhs,lhs);});
 const c=store();await c.S.init();c.S.setCourse('rishoni');
 await c.S.save({id:'older',flownAt:'2026-08-01',stage:'brief',answers:{q_subject:'AW 3'}});
 await c.S.save({id:'newer',flownAt:'2026-08-03',stage:'done',answers:{q_subject:'AW 4',q_goals_next:[{text:'newer goal'}]}});
 await c.S.save({id:'older',stage:'done',answers:{q_subject:'AW 3'}});
 check('out-of-order first debrief preserves newer goal',()=>assert.equal(c.S.nextGoals()[0].text,'newer goal'));
 const copies=store();await copies.S.init();
 await copies.S.save({id:'old-aw',flownAt:'2026-08-01',stage:'done',answers:{q_subject:'AW 3'}});
 await copies.S.save({id:'new-navigation',flownAt:'2026-08-03',stage:'done',answers:{q_subject:'ניווט 3',q_goals_next:[{text:'same wording'}]}});
 await copies.S.save({id:'old-aw',stage:'done',answers:{q_subject:'AW 3',q_goals:[{text:'same wording',status:'missed'}]}});
 check('G02 old-flight edit preserves identical wording in different categories',()=>{
  const shelf=JSON.parse(JSON.stringify(copies.S.nextGoals()));
  assert.equal(shelf.length,2);assert.ok(shelf.some(g=>g.from==='old-aw'&&g.cats.includes('AW')));assert.ok(shelf.some(g=>g.from==='new-navigation'&&g.cats.includes('ניווט')));
 });
 const aw=c.S.get('older');c.S.setCourse('mitkadem');
 check('historical categories use record course',()=>assert.deepEqual(Array.from(c.S.categoriesOf(aw)),['AW']));
 check('course goals do not cross courses',()=>assert.equal(c.S.pendingGoalsFor(['AW']).length,0));
 [['לילה מתקדם 1','לילה מתקדם'],['יירוטים ב 1','יירוטים ב'],['הכנה למסכמות 1','הכנה למסכמות']].forEach(([text,cat])=>check('specific category '+text,()=>assert.deepEqual(Array.from(c.S.categoriesInText(text)),[cat])));
 const f=store({}, {failWrites:true});await f.S.init();await assert.rejects(f.S.save({answers:{q_subject:'unsaved'}}));check('failed storage rejects Save',()=>assert.equal(f.S.count(),0));
 const q=store();await q.S.init();await q.S.save({id:'historical',stage:'done',answers:{q_points:[{text:'preserved'}]}});
 const version=q.S.updateQuestion('q_points',{type:'text'});
 check('retyping versions the question and preserves old answer',()=>{assert.notEqual(version.id,'q_points');assert.equal(q.S.question('q_points').type,'list');assert.ok(q.S.asText(q.S.get('historical')).includes('preserved'));});
 const custom=q.S.addQuestion({id:'custom',label:'Custom',type:'text'});await q.S.save({id:'custom-record',answers:{[custom.id]:'find me'}});q.S.resetQuestions();
 check('reset retains historical custom definitions',()=>{assert.equal(q.S.question('custom').archived,true);assert.equal(q.S.search('find me').length,1);});
 q.S.set('startDismissed',true);q.S.saveDraft({id:'orphan',answers:{q_subject:'old work'}},'debrief');const reloaded=store(q.mem);await reloaded.S.init();
 check('dismissal and orphan drafts survive reload',()=>{assert.equal(reloaded.S.settings().startDismissed,true);assert.ok(reloaded.S.readDraft('orphan','debrief'));});
 const oldVersion=q.S.get('historical').updatedAt;await q.S.save({id:'historical',answers:{q_subject:'new'}});
 await assert.rejects(q.S.save({id:'historical',baseUpdatedAt:oldVersion,answers:{q_subject:'stale'}}));checks++;console.log('PASS stale record edit is rejected');
 await q.S.remove('historical');check('delete is recoverable',()=>assert.ok(q.S.trash().some(r=>r.id==='historical')));await q.S.restore(q.S.trash().find(r=>r.id==='historical').record);
 const restored=store(q.mem);await restored.S.init();check('restore survives reload without tombstone resurrection',()=>assert.ok(restored.S.get('historical')));
 a.W.deleteNote(note.id);a.W.restoreNote(note.id);a.W.removeFolder(folder.id);
 check('note restore and folder delete preserve text',()=>{assert.equal(a.W.note(note.id).body,'תוכן עברי');assert.equal(a.W.note(note.id).folder,'');});
 const damaged=store({'sortie:mirror':'{"not":"an array"}'});await damaged.S.init();check('bad mirror is quarantined',()=>assert.ok(damaged.mem['sortie:damaged-mirror']));
 const malformed=store({'sortie:mirror':'broken JSON'});await malformed.S.init();check('unparseable mirror is preserved verbatim',()=>assert.equal(malformed.mem['sortie:damaged-mirror'],'broken JSON'));
 const settingsOptions={failWrites:false},settingsFailure=store({},settingsOptions);await settingsFailure.S.init();const settingsBefore=JSON.stringify(settingsFailure.S.settings());settingsOptions.failWrites=true;
 check('failed question and shelf edits roll back memory',()=>{assert.throws(()=>settingsFailure.S.addQuestion({label:'lost'}));assert.throws(()=>settingsFailure.S.addNextGoal('lost'));assert.equal(JSON.stringify(settingsFailure.S.settings()),settingsBefore);});
 const source=store();await source.S.init();source.S.updateQuestion('q_points',{type:'text'});await source.S.save({id:'incoming',answers:{q_points:'incoming text'}});source.W.saveFeedback({id:'feedback',message:'feedback draft'});
 const target=store();await target.S.init();await target.S.save({id:'retained',answers:{q_points:[{id:'point',text:'structured original'}]}});await target.S.importJSON(source.S.toJSON(),{restorePreferences:true});
 check('import keeps both definitions and historical answer shapes',()=>{assert.equal(target.S.question('q_points').type,'list');assert.equal(target.S.get('retained').answers.q_points[0].text,'structured original');assert.equal(target.S.get('incoming').answers.q_points_import_text,'incoming text');assert.ok(target.S.asText(target.S.get('incoming')).includes('incoming text'));});
 check('feedback draft participates in full backup',()=>assert.equal(target.W.feedbackDraft().message,'feedback draft'));
 const journalStore=store();await journalStore.S.init();const desired=JSON.stringify([{id:'interrupted',updatedAt:123,answers:{q_subject:'retained'}}]);journalStore.mem['sortie:transaction']=JSON.stringify({state:'apply',before:{'sortie:mirror':'[]'},after:{'sortie:mirror':desired}});
 const recovered=store(journalStore.mem);await recovered.S.init();check('interrupted durable intent completes on boot',()=>{assert.ok(recovered.S.get('interrupted'));assert.equal(recovered.mem['sortie:transaction'],undefined);});
 const legacy=store({'sortie:mirror':JSON.stringify([{id:'legacy',answers:{q_subject:'AW 3'}}])});await legacy.S.init();const tags=Array.from(legacy.S.categoriesOf(legacy.S.get('legacy')));legacy.S.setCourse('mitkadem');check('unknown course stays unassigned and text filters stay stable',()=>{assert.equal(legacy.S.get('legacy').course,null);assert.deepEqual(Array.from(legacy.S.categoriesOf(legacy.S.get('legacy'))),tags);});
 const milestone=a.W.all().milestones[0];a.W.deleteMilestone(milestone.id);a.W.restoreMilestone(milestone.id);check('deleted milestones remain recoverable',()=>assert.equal(a.W.all().milestones[0].deletedAt,null));
 a.S.promoteDraft({answers:{q_subject:'orphan to reopen'}});check('reopening orphan retains the existing new brief too',()=>{assert.equal(a.S.readDraft().answers.q_subject,'orphan to reopen');assert.ok(Object.values(a.S.drafts()).some(raw=>JSON.parse(raw).rec.buffers?.['goalinput:q_goals']==='unfinished'));});
 console.log(checks+' preservation checks passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
